### PR TITLE
Bump runtime and remove unneded dependencies/dconf access

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I don't have any audio books, so please test this.

**Comment by geigi** [comment]
I‘ll have to test the dconf access but the gstreamer plugins are definitely needed to support all the audio files I want to support.

**Comment by bilelmoussaoui** [comment]
> I‘ll have to test the dconf access

https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/. I forgot to add the `--metadata=X-DConf=migrate-path=/com/github/geigi/cozy/ ` to finish-args to migrate the old settings, but it should work.

>  but the gstreamer plugins are definitely needed to support all the audio files I want to support.

Those plugins are part of GNOME SDK, there's just no need to rebuild them here.

**Comment by geigi** [comment]
> Those plugins are part of GNOME SDK, there's just no need to rebuild them here.
I see, thanks for clarifying! And thanks for your contributions. I gave the test build a run and everything seems to be fine. 

It's awesome how much this speed up the build process 🚀️

**Pull request merged**
