### PR TITLE
Runtime 45

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
cc @geigi

**Comment by azzamsa** [comment]
Come here for the same reason.

```
Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
   
Info: applications using this runtime:
   com.github.geigi.cozy
```

**Comment by bbhtt** [comment]
Can you test https://github.com/flathub/com.github.geigi.cozy/pull/9#issuecomment-1732878833?

I can merge if the maintainer does not respond.

**Comment by azzamsa** [comment]
> Can you test [#9 (comment)](https://github.com/flathub/com.github.geigi.cozy/pull/9#issuecomment-1732878833)?
> 
> I can merge if the maintainer does not respond.

Sorry, this is my first time installing the edge version. Will it override my current stable installation? Otherwise, I am okay with it.

**Comment by bbhtt** [comment]
> Sorry, this is my first time installing the edge version. Will it override my current stable installation? Otherwise, I am okay with it.

No, it won't. You can run it as `flatpak run app/com.github.geigi.cozy/x86_64/test`

Test the next build please, that one was broken due to the python updates. I have dropped that.

**Comment by azzamsa** [comment]
> Build [68827 successful](https://buildbot.flathub.org/#/builders/6/builds/68827) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/51474/com.github.geigi.cozy.flatpakref
> ```

Works fine for me. All Tabs, playback speed, volume. All works fine.
But, I don't try sleep timer.

**Comment by bbhtt** [comment]
Merging, thanks.

You can remove it now, `flatpak remove`, then choose the one that has "test".

You'll receive an update in 4-5 hours

**Comment by azzamsa** [comment]
Thank you for fixing this issue! 🏅

**Pull request merged**
